<?php
return [
    // 'siigo_api_url' => env('SIIGO_API_URL'),
    // 'siigo_api_token_url' => env('SIIGO_API_TOKEN_URL'),
    // 'siigo_timeout' => env('SIIGO_TIMEOUT'),
    // 'siigo_basic_authorization' => env('SIIGO_BASIC_AUTHORIZATION'),
    // 'siigo_namespace' => env('SIIGO_NAMESPACE'),
    // 'siigo_grant_type' => env('SIIGO_GRANT_TYPE'),
    // 'siigo_user_name' => env('SIIGO_USER_NAME'),
    // 'siigo_user_api' => env('SIIGO_USER_API'),
    // 'siigo_password' => env('SIIGO_PASSWORD'),
    // 'siigo_scope' => env('SIIGO_SCOPE'),
    // 'siigo_token_expired_at_days' => env('SIIGO_TOKEN_EXPIRED_AT_DAYS'),
    // 'siigo_ocp_apim_subscription_key' =>  env('SIIGO_OCP_APIM_SUBSCRIPTION_KEY'),
    // 'siigo_payment_means_expired' => env('SIIGO_PAYMENT_MEANS_EXPIRED'),
    // 'siigo_default_paymentmean' => env('SIIGO_DEFAULT_PAYMENTMEAN'),
    // 'siigo_data_user_expired' => env('SIIGO_DATA_USER_EXPIRED'),
    // 'siigo_money_code' => env('SIIGO_MONEY_CODE'),
    // 'siigo_full_name' => env('SIIGO_FULL_NAME'),
    // 'siigo_id_type_code' => env('SIIGO_ID_TYPE_CODE'),
    // 'siigo_is_vat_company_type' => env('SIIGO_IS_VAT_COMPANY_TYPE'),
    // 'siigo_country_code' => env('SIIGO_COUNTRY_CODE'),
    // 'siigo_phone_indicative' => env('SIIGO_PHONE_INDICATIVE'),
    // 'siigo_phone_number' => env('SIIGO_PHONE_NUMBER'),
    // 'siigo_phone_extention' => env('SIIGO_PHONE_EXTENTION'),
    // 'siigo_is_customer' => env('SIIGO_IS_CUSTOMER'),
    // 'siigo_default_doc_code' => env('SIIGO_DEFAULT_DOC_CODE'),
    // 'siigo_voucher_branch_office_default' => env('SIIGO_VOUCHER_BRANCH_OFFICE_DEFAULT'),
    // 'siigo_type_invoice_default' => env('SIIGO_TYPE_INVOICE_DEFAULT'),
    // 'siigo_voucher_paymeant_default' => env('SIIGO_VOUCHER_PAYMEANT_DEFAULT'),
    // 'siigo_invoice_default_observation' => env('SIIGO_INVOICE_DEFAULT_OBSERVATION'),
    // 'siigo_voucher_default_observation' => env('SIIGO_VOUCHER_DEFAULT_OBSERVATION'),
    // 'siigo_voucher_item_observation' => env('SIIGO_VOUCHER_ITEM_OBSERVATION'),
    // 'siigo_debit_efecty_account_bank' => env('SIIGO_DEBIT_EFECTY_ACCOUNT_BANK'),
    // 'siigo_task_create_client_account' => env('SIIGO_TASK_CREATE_CLIENT_ACCOUNT'),
    // 'siigo_voucher_payment_mean_default' => env('SIIGO_VOUCHER_PAYMENT_MEAN_DEFAULT'),
    // // API VERSION 2
    'siigo_api_token_url_v2' => env('SIIGO_API_TOKEN_URL_V2'),
    'siigo_user_name_v2' => env('SIIGO_USER_NAME_V2'),
    'siigo_access_key_v2' => env('SIIGO_ACCESS_KEY_V2'),
    'siigo_timeout_api' => env('SIIGO_TIMEOUT_API'),
    'siigo_currency_code' => env('SIIGO_CURRENCY_CODE', 'COP'),
    'siigo_currency_exchange_rate' => env('SIIGO_CURRENCY_EXCHANGE_RATE', '3825.03'),
    'siigo_default_payment_type' => env('SIIGO_DEFAULT_PAYMENT_TYPE', 'Efectivo'),
    'siigo_default_invoice_document' => env('SIIGO_DEFAULT_INVOICE_DOCUMENT', 18503),
    'siigo_default_invoice_observation' => env('SIIGO_DEFAULT_INVOICE_OBSERVATION', 'Si ya realizó su pago, por favor hacer caso omiso.'),
    'siigo_default_days_limit_diam' => env('SIIGO_DEFAULT_DAYS_LIMIT_DIAM', 10),
    
];